<a href="https://colab.research.google.com/github/Foysal348/Perceptron-Classification-on-Iris-Dataset-Scikit-Learn-/blob/main/DL_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [69]:

class Percepton:
  def __init__(self,eta,epochs):
    self.eta = eta
    self.epochs = epochs
    self.weights = np.random.randn(3) * 1e-4
    print("Initial Weights:", self.weights)


  def ActivationFunction(self,inputs,weights):
    z=np.dot(inputs,weights)
    return np.where(z>0,1,0)

  def fit(self,X,y):
    self.X=X
    self.Y=y
    X_with_bias=np.c_[self.X,-np.ones(len(X))]
    print(f"X with bias:{X_with_bias}")

    for epoch in range(self.epochs):
     print(f"Epochs :{epoch+1}")
     y_hat=self.ActivationFunction(X_with_bias, self.weights)
     print(f"Y_hat:{y_hat}")

     error=self.Y-y_hat
     print(f"Error:\n{error}")

     if np.all(error == 0):
          print("Training converged!")
          break
     #Weight Update
     self.weights=self.weights+self.eta*np.dot(X_with_bias.T,error)
     print(f"Updated weight:{self.weights}")

  def predict(self,X) :
    X_with_bias=np.c_[X,-np.ones(len(X))]
    return self.ActivationFunction(X_with_bias,self.weights)


In [70]:
data={
    "X1":[0,1,0,1],
    "X2":[0,0,1,1],
    "Output":[0,0,0,1],
}
df=pd.DataFrame(data)
X=df.drop(["Output"],axis=1)
y=df["Output"]
y.to_frame()

Output
0       0
1       0
2       0
3       1

In [71]:
model=Percepton(eta=0.5,epochs=10)
model.fit(X,y)

Initial Weights: [-8.80591266e-05 -1.13055230e-04  1.34428883e-05]
X with bias:[[ 0.  0. -1.]
 [ 1.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  1. -1.]]
Epochs :1
Y_hat:[0 0 0 0]
Error:
0    0
1    0
2    0
3    1
Name: Output, dtype: int64
Updated weight:[ 0.49991194  0.49988694 -0.49998656]
Epochs :2
Y_hat:[1 1 1 1]
Error:
0   -1
1   -1
2   -1
3    0
Name: Output, dtype: int64
Updated weight:[-8.80591266e-05 -1.13055230e-04  1.00001344e+00]
Epochs :3
Y_hat:[0 0 0 0]
Error:
0    0
1    0
2    0
3    1
Name: Output, dtype: int64
Updated weight:[0.49991194 0.49988694 0.50001344]
Epochs :4
Y_hat:[0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: Output, dtype: int64
Training converged!
